import { Pool, neonConfig } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-serverless';
import ws from "ws";
import * as schema from "@shared/schema";

neonConfig.webSocketConstructor = ws;

if (!process.env.DATABASE_URL) {
  throw new Error(
    "DATABASE_URL must be set. Did you forget to provision a database?",
  );
}

export const pool = new Pool({ connectionString: process.env.DATABASE_URL });
export const db = drizzle({ client: pool, schema });

const categories: ServiceCategory[] = [
  { id: 1, name: "Air Condition", nameAr: "تكييف الهواء", icon: "❄️" },
  { id: 2, name: "Plumbing", nameAr: "السباكة", icon: "🔧" },
  { id: 3, name: "Electrical", nameAr: "الكهرباء", icon: "⚡" },
  { id: 4, name: "Cleaning", nameAr: "التنظيف", icon: "🧹" },
  { id: 5, name: "Painting", nameAr: "الدهان", icon: "🎨" },
  { id: 6, name: "Carpentry", nameAr: "النجارة", icon: "🔨" },
  { id: 7, name: "Landscaping", nameAr: "تنسيق الحدائق", icon: "🌿" },
  { id: 8, name: "Pest Control", nameAr: "مكافحة الآفات", icon: "🐛" },
  { id: 9, name: "Security Systems", nameAr: "أنظمة الأمان", icon: "🛡️" },
  { id: 10, name: "Home Appliances", nameAr: "الأجهزة المنزلية", icon: "📱" },
  { id: 11, name: "Roofing", nameAr: "أعمال الأسطح", icon: "🏠" },
  { id: 12, name: "Flooring", nameAr: "أعمال الأرضيات", icon: "🔲" },
  { id: 13, name: "Kitchen & Bath", nameAr: "المطابخ والحمامات", icon: "🚿" },
  { id: 14, name: "Windows & Doors", nameAr: "النوافذ والأبواب", icon: "🚪" },
  { id: 15, name: "Solar Energy", nameAr: "الطاقة الشمسية", icon: "☀️" },
  { id: 16, name: "Moving Services", nameAr: "خدمات النقل", icon: "📦" },
  { id: 17, name: "Interior Design", nameAr: "التصميم الداخلي", icon: "🎨" },
  { id: 18, name: "Computer Repair", nameAr: "إصلاح الحاسوب", icon: "💻" },
  { id: 19, name: "Television Repair", nameAr: "إصلاح التلفزيون", icon: "📺" },
  { id: 20, name: "Satellite Installation", nameAr: "تركيب الأقمار الصناعية", icon: "📡" },
  { id: 21, name: "Car Wash", nameAr: "غسيل السيارات", icon: "🚗" },
  { id: 22, name: "Pool Maintenance", nameAr: "صيانة المسابح", icon: "🏊" },
  { id: 23, name: "Photography", nameAr: "التصوير الفوتوغرافي", icon: "📸" },
  { id: 24, name: "Event Planning", nameAr: "تنظيم الفعاليات", icon: "🎉" },
  { id: 25, name: "Legal Services", nameAr: "الخدمات القانونية", icon: "⚖️" },
  { id: 26, name: "Accounting", nameAr: "المحاسبة", icon: "📊" },
  { id: 27, name: "Tutoring", nameAr: "الدروس الخصوصية", icon: "📚" },
  { id: 28, name: "Pet Care", nameAr: "رعاية الحيوانات الأليفة", icon: "🐕" },
  { id: 29, name: "Catering", nameAr: "خدمات الطعام", icon: "🍽️" },
  { id: 30, name: "Fitness Training", nameAr: "التدريب الرياضي", icon: "💪" },
];

const providers: ServiceProvider[] = [
  // Air Conditioning Providers
  {
    id: 1,
    name: "Ahmed Al-Baghdadi",
    email: "ahmed@example.com",
    phone: "+964 770 123 4567",
    categoryId: 1,
    cityId: 1,
    rating: 4.8,
    completedJobs: 156,
    description: "Professional AC technician with 10+ years experience in installation and repair.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 2 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 2,
    name: "Kareem Al-Najafi",
    email: "kareem@example.com",
    phone: "+964 770 111 2222",
    categoryId: 1,
    cityId: 5,
    rating: 4.9,
    completedJobs: 234,
    description: "Expert in central air conditioning systems and energy-efficient solutions.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 1 hour",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  // Plumbing Providers
  {
    id: 3,
    name: "Sara Mohammed",
    email: "sara@example.com",
    phone: "+964 770 234 5678",
    categoryId: 2,
    cityId: 2,
    rating: 4.9,
    completedJobs: 203,
    description: "Expert plumber specializing in residential and commercial plumbing solutions.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: false,
    responseTime: "within 4 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 4,
    name: "Hassan Al-Basri",
    email: "hassan@example.com",
    phone: "+964 770 333 4444",
    categoryId: 2,
    cityId: 2,
    rating: 4.7,
    completedJobs: 178,
    description: "Professional plumber with expertise in modern plumbing systems and emergency repairs.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 3 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  // Electrical Providers
  {
    id: 5,
    name: "Omar Hassan",
    email: "omar@example.com",
    phone: "+964 770 345 6789",
    categoryId: 3,
    cityId: 3,
    rating: 4.7,
    completedJobs: 127,
    description: "Licensed electrician providing safe and reliable electrical services.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 1 hour",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 6,
    name: "Zaid Al-Karkhi",
    email: "zaid@example.com",
    phone: "+964 770 555 6666",
    categoryId: 3,
    cityId: 1,
    rating: 4.8,
    completedJobs: 189,
    description: "Experienced electrical engineer specializing in smart home installations.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 2 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  // Cleaning Providers
  {
    id: 7,
    name: "Fatima Al-Zahra",
    email: "fatima@example.com",
    phone: "+964 770 777 8888",
    categoryId: 4,
    cityId: 1,
    rating: 4.9,
    completedJobs: 312,
    description: "Professional cleaning service with eco-friendly products and thorough attention to detail.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 4 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 8,
    name: "Maryam Al-Baghdadi",
    email: "maryam@example.com",
    phone: "+964 770 999 0000",
    categoryId: 4,
    cityId: 3,
    rating: 4.6,
    completedJobs: 145,
    description: "Reliable house cleaning service specializing in deep cleaning and maintenance.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: false,
    responseTime: "within 6 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  // Painting Providers
  {
    id: 9,
    name: "Ali Al-Mosuli",
    email: "ali@example.com",
    phone: "+964 770 111 3333",
    categoryId: 5,
    cityId: 4,
    rating: 4.8,
    completedJobs: 98,
    description: "Professional painter with expertise in interior and exterior painting projects.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 5 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 10,
    name: "Amjad Al-Erbili",
    email: "amjad@example.com",
    phone: "+964 770 222 4444",
    categoryId: 5,
    cityId: 3,
    rating: 4.7,
    completedJobs: 156,
    description: "Expert painter specializing in decorative finishes and custom color schemes.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 3 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  // Carpentry Providers
  {
    id: 11,
    name: "Mohammed Al-Najjar",
    email: "mohammed@example.com",
    phone: "+964 770 333 5555",
    categoryId: 6,
    cityId: 1,
    rating: 4.9,
    completedJobs: 287,
    description: "Master carpenter with 15+ years experience in custom furniture and woodwork.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 2 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 12,
    name: "Yusuf Al-Karbali",
    email: "yusuf@example.com",
    phone: "+964 770 444 6666",
    categoryId: 6,
    cityId: 2,
    rating: 4.6,
    completedJobs: 134,
    description: "Skilled carpenter specializing in kitchen cabinets and built-in storage solutions.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: false,
    responseTime: "within 8 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  // Landscaping Providers
  {
    id: 13,
    name: "Nadia Al-Hadra",
    email: "nadia@example.com",
    phone: "+964 770 555 7777",
    categoryId: 7,
    cityId: 1,
    rating: 4.8,
    completedJobs: 89,
    description: "Professional landscaper creating beautiful outdoor spaces and garden designs.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 4 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 14,
    name: "Khalil Al-Zahir",
    email: "khalil@example.com",
    phone: "+964 770 666 8888",
    categoryId: 7,
    cityId: 3,
    rating: 4.7,
    completedJobs: 76,
    description: "Garden maintenance specialist with expertise in irrigation and plant care.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 6 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  // Pest Control Providers
  {
    id: 15,
    name: "Sabah Al-Ameen",
    email: "sabah@example.com",
    phone: "+964 770 777 9999",
    categoryId: 8,
    cityId: 2,
    rating: 4.9,
    completedJobs: 165,
    description: "Licensed pest control specialist using safe and effective treatment methods.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 3 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  // Security Systems Providers
  {
    id: 16,
    name: "Raed Al-Amni",
    email: "raed@example.com",
    phone: "+964 770 888 0000",
    categoryId: 9,
    cityId: 1,
    rating: 4.8,
    completedJobs: 112,
    description: "Security systems expert installing CCTV, alarms, and smart security solutions.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 2 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  // Home Appliances Providers
  {
    id: 17,
    name: "Tariq Al-Tekni",
    email: "tariq@example.com",
    phone: "+964 770 999 1111",
    categoryId: 10,
    cityId: 4,
    rating: 4.7,
    completedJobs: 198,
    description: "Home appliance repair specialist for refrigerators, washers, and electronics.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 4 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  // Roofing Providers
  {
    id: 18,
    name: "Waleed Al-Saqf",
    email: "waleed@example.com",
    phone: "+964 770 000 2222",
    categoryId: 11,
    cityId: 1,
    rating: 4.9,
    completedJobs: 87,
    description: "Professional roofer specializing in repair, replacement, and waterproofing.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 5 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  // Flooring Providers
  {
    id: 19,
    name: "Salam Al-Ard",
    email: "salam@example.com",
    phone: "+964 770 111 4444",
    categoryId: 12,
    cityId: 2,
    rating: 4.6,
    completedJobs: 143,
    description: "Flooring contractor specializing in tiles, marble, and wooden floor installation.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: false,
    responseTime: "within 7 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  // Additional providers for various categories
  {
    id: 20,
    name: "Layla Al-Matbakh",
    email: "layla@example.com",
    phone: "+964 770 222 5555",
    categoryId: 13,
    cityId: 3,
    rating: 4.8,
    completedJobs: 167,
    description: "Kitchen and bathroom renovation specialist with modern design expertise.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 3 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 21,
    name: "Haider Al-Nafitha",
    email: "haider@example.com",
    phone: "+964 770 333 6666",
    categoryId: 14,
    cityId: 1,
    rating: 4.7,
    completedJobs: 124,
    description: "Windows and doors installation expert with quality materials and craftsmanship.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 4 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 22,
    name: "Nour Al-Shams",
    email: "nour@example.com",
    phone: "+964 770 444 7777",
    categoryId: 15,
    cityId: 5,
    rating: 4.9,
    completedJobs: 95,
    description: "Solar energy systems installer providing clean and sustainable energy solutions.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 2 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 23,
    name: "Rami Al-Naql",
    email: "rami@example.com",
    phone: "+964 770 555 8888",
    categoryId: 16,
    cityId: 2,
    rating: 4.6,
    completedJobs: 234,
    description: "Professional moving service with careful handling and reliable transportation.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 6 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 24,
    name: "Dina Al-Tasmeem",
    email: "dina@example.com",
    phone: "+964 770 666 9999",
    categoryId: 17,
    cityId: 1,
    rating: 4.8,
    completedJobs: 78,
    description: "Interior designer creating beautiful and functional living spaces.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 5 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 25,
    name: "Saad Al-Hasub",
    email: "saad@example.com",
    phone: "+964 770 777 0000",
    categoryId: 18,
    cityId: 4,
    rating: 4.7,
    completedJobs: 156,
    description: "Computer repair technician specializing in hardware and software solutions.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 3 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 26,
    name: "Qasim Al-Tilaz",
    email: "qasim@example.com",
    phone: "+964 770 888 1111",
    categoryId: 19,
    cityId: 3,
    rating: 4.8,
    completedJobs: 189,
    description: "Television repair expert with experience in all major brands and models.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 4 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 27,
    name: "Basim Al-Qamar",
    email: "basim@example.com",
    phone: "+964 770 999 2222",
    categoryId: 20,
    cityId: 1,
    rating: 4.9,
    completedJobs: 134,
    description: "Satellite installation specialist providing HD and digital reception solutions.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 2 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 28,
    name: "Jamal Al-Sayara",
    email: "jamal@example.com",
    phone: "+964 770 000 3333",
    categoryId: 21,
    cityId: 2,
    rating: 4.6,
    completedJobs: 267,
    description: "Professional car wash service with eco-friendly products and detailing.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 5 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 29,
    name: "Yasmin Al-Sibaha",
    email: "yasmin@example.com",
    phone: "+964 770 111 5555",
    categoryId: 22,
    cityId: 5,
    rating: 4.8,
    completedJobs: 89,
    description: "Pool maintenance specialist ensuring clean and safe swimming environments.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 4 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 30,
    name: "Mazen Al-Tasweer",
    email: "mazen@example.com",
    phone: "+964 770 222 6666",
    categoryId: 23,
    cityId: 1,
    rating: 4.9,
    completedJobs: 145,
    description: "Professional photographer specializing in events, portraits, and commercial photography.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 3 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  // Continue with more providers for remaining categories
  {
    id: 31,
    name: "Rana Al-Hafla",
    email: "rana@example.com",
    phone: "+964 770 333 7777",
    categoryId: 24,
    cityId: 3,
    rating: 4.8,
    completedJobs: 67,
    description: "Event planning expert creating memorable occasions for all types of celebrations.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 6 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 32,
    name: "Adel Al-Qanun",
    email: "adel@example.com",
    phone: "+964 770 444 8888",
    categoryId: 25,
    cityId: 1,
    rating: 4.7,
    completedJobs: 98,
    description: "Legal services consultant providing professional advice and document preparation.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: false,
    responseTime: "within 12 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 33,
    name: "Widad Al-Hasabat",
    email: "widad@example.com",
    phone: "+964 770 555 9999",
    categoryId: 26,
    cityId: 2,
    rating: 4.9,
    completedJobs: 156,
    description: "Certified accountant providing bookkeeping, tax preparation, and financial consulting.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 4 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 34,
    name: "Hasan Al-Modarres",
    email: "hasan@example.com",
    phone: "+964 770 666 0000",
    categoryId: 27,
    cityId: 4,
    rating: 4.8,
    completedJobs: 234,
    description: "Private tutor specializing in mathematics, science, and English language instruction.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 2 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 35,
    name: "Nada Al-Hayawan",
    email: "nada@example.com",
    phone: "+964 770 777 1111",
    categoryId: 28,
    cityId: 1,
    rating: 4.9,
    completedJobs: 189,
    description: "Pet care specialist providing grooming, training, and veterinary assistance.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 3 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 36,
    name: "Karim Al-Taem",
    email: "karim@example.com",
    phone: "+964 770 888 2222",
    categoryId: 29,
    cityId: 3,
    rating: 4.7,
    completedJobs: 123,
    description: "Professional catering service specializing in traditional Iraqi and international cuisine.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 8 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 37,
    name: "Laith Al-Riada",
    email: "laith@example.com",
    phone: "+964 770 999 3333",
    categoryId: 30,
    cityId: 5,
    rating: 4.8,
    completedJobs: 167,
    description: "Certified fitness trainer providing personalized workout plans and nutrition guidance.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 4 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  // Add more providers to reach 50+
  {
    id: 38,
    name: "Ameer Al-Bareed",
    email: "ameer@example.com",
    phone: "+964 770 111 7777",
    categoryId: 1,
    cityId: 3,
    rating: 4.7,
    completedJobs: 98,
    description: "AC installation specialist with expertise in energy-efficient cooling systems.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 3 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 39,
    name: "Zina Al-Miyah",
    email: "zina@example.com",
    phone: "+964 770 222 8888",
    categoryId: 2,
    cityId: 4,
    rating: 4.8,
    completedJobs: 145,
    description: "Plumbing expert specializing in bathroom renovations and pipe installations.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 2 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 40,
    name: "Samer Al-Kahraba",
    email: "samer@example.com",
    phone: "+964 770 333 9999",
    categoryId: 3,
    cityId: 2,
    rating: 4.9,
    completedJobs: 201,
    description: "Licensed electrician with expertise in industrial and residential electrical work.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 1 hour",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  // Continue adding more providers to reach 50+
  {
    id: 41,
    name: "Huda Al-Nadhafa",
    email: "huda@example.com",
    phone: "+964 770 444 0000",
    categoryId: 4,
    cityId: 5,
    rating: 4.6,
    completedJobs: 134,
    description: "Commercial cleaning specialist for offices and retail spaces.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: false,
    responseTime: "within 5 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 42,
    name: "Muneer Al-Dahan",
    email: "muneer@example.com",
    phone: "+964 770 555 1111",
    categoryId: 5,
    cityId: 1,
    rating: 4.8,
    completedJobs: 167,
    description: "Decorative painter specializing in artistic wall finishes and murals.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 4 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 43,
    name: "Farah Al-Khashab",
    email: "farah@example.com",
    phone: "+964 770 666 2222",
    categoryId: 6,
    cityId: 3,
    rating: 4.7,
    completedJobs: 89,
    description: "Custom furniture maker specializing in handcrafted wooden pieces.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 6 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 44,
    name: "Ghassan Al-Bustani",
    email: "ghassan@example.com",
    phone: "+964 770 777 3333",
    categoryId: 7,
    cityId: 2,
    rating: 4.9,
    completedJobs: 156,
    description: "Landscape architect creating sustainable garden designs and outdoor living spaces.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 3 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 45,
    name: "Thuraya Al-Mukafaha",
    email: "thuraya@example.com",
    phone: "+964 770 888 4444",
    categoryId: 8,
    cityId: 1,
    rating: 4.8,
    completedJobs: 178,
    description: "Integrated pest management specialist using environmentally safe methods.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 2 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 46,
    name: "Rashid Al-Himaya",
    email: "rashid@example.com",
    phone: "+964 770 999 5555",
    categoryId: 9,
    cityId: 4,
    rating: 4.7,
    completedJobs: 123,
    description: "Security consultant specializing in home automation and surveillance systems.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: false,
    responseTime: "within 8 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 47,
    name: "Sawsan Al-Ajhiza",
    email: "sawsan@example.com",
    phone: "+964 770 000 6666",
    categoryId: 10,
    cityId: 5,
    rating: 4.9,
    completedJobs: 234,
    description: "Home appliance technician with expertise in smart home device installation.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 3 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 48,
    name: "Thaer Al-Sath",
    email: "thaer@example.com",
    phone: "+964 770 111 8888",
    categoryId: 11,
    cityId: 1,
    rating: 4.6,
    completedJobs: 145,
    description: "Roofing contractor specializing in traditional and modern roofing materials.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 5 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 49,
    name: "Iman Al-Balat",
    email: "iman@example.com",
    phone: "+964 770 222 9999",
    categoryId: 12,
    cityId: 3,
    rating: 4.8,
    completedJobs: 167,
    description: "Flooring expert specializing in luxury vinyl and hardwood installations.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 4 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"]
  },
  {
    id: 50,
    name: "Khaled Al-Matbakh",
    email: "khaled@example.com",
    phone: "+964 770 333 0000",
    categoryId: 13,
    cityId: 2,
    rating: 4.7,
    completedJobs: 189,
    description: "Kitchen renovation specialist with modern design and functionality expertise.",
    profileImage: "/api/placeholder/150/150",
    isVerified: true,
    isOnline: true,
    responseTime: "within 6 hours",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200", "/api/placeholder/300/200"]
  }
];