import { Pool, neonConfig } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-serverless';
import ws from "ws";
import * as schema from "@shared/schema";

neonConfig.webSocketConstructor = ws;

if (!process.env.DATABASE_URL) {
  throw new Error(
    "DATABASE_URL must be set. Did you forget to provision a database?",
  );
}

export const pool = new Pool({ connectionString: process.env.DATABASE_URL });
export const db = drizzle({ client: pool, schema });

const categories: Omit<schema.ServiceCategory, 'id'>[] = [
  { name: "Air Condition", nameAr: "تكييف الهواء", icon: "fas fa-snowflake", color: "#4caf50" },
  { name: "Plumbing", nameAr: "السباكة", icon: "fas fa-wrench", color: "#06b6d4" },
  { name: "Cleaning", nameAr: "التنظيف", icon: "fas fa-broom", color: "#4caf50" },
  { name: "Painter", nameAr: "الدهان", icon: "fas fa-paint-brush", color: "#f59e0b" },
  { name: "Carpenter", nameAr: "النجارة", icon: "fas fa-hammer", color: "#8b5cf6" },
  { name: "Electrical", nameAr: "الكهرباء", icon: "fas fa-bolt", color: "#eab308" },
  { name: "Gardening", nameAr: "البستنة", icon: "fas fa-leaf", color: "#4caf50" },
  { name: "Moving", nameAr: "النقل", icon: "fas fa-truck", color: "#f97316" },
  { name: "Roofing", nameAr: "تسقيف", icon: "fas fa-home", color: "#7c3aed" },
  { name: "Flooring", nameAr: "أرضيات", icon: "fas fa-square", color: "#dc2626" },
  { name: "Tiling", nameAr: "بلاط", icon: "fas fa-th", color: "#0891b2" },
  { name: "Welding", nameAr: "لحام", icon: "fas fa-fire", color: "#ea580c" },
  { name: "Glass Work", nameAr: "أعمال الزجاج", icon: "fas fa-glass", color: "#06b6d4" },
  { name: "Masonry", nameAr: "بناء", icon: "fas fa-cube", color: "#78716c" },
  { name: "Security Systems", nameAr: "أنظمة أمنية", icon: "fas fa-shield-alt", color: "#dc2626" },
  { name: "Pest Control", nameAr: "مكافحة الآفات", icon: "fas fa-bug", color: "#4caf50" },
  { name: "Appliance Repair", nameAr: "إصلاح الأجهزة", icon: "fas fa-tools", color: "#3b82f6" },
  { name: "Furniture Assembly", nameAr: "تجميع الأثاث", icon: "fas fa-couch", color: "#8b5cf6" },
  { name: "TV Mounting", nameAr: "تركيب التلفزيون", icon: "fas fa-tv", color: "#1f2937" },
  { name: "Pool Maintenance", nameAr: "صيانة المسابح", icon: "fas fa-swimmer", color: "#06b6d4" },
  { name: "Solar Panel Installation", nameAr: "تركيب الألواح الشمسية", icon: "fas fa-solar-panel", color: "#eab308" },
  { name: "Satellite Installation", nameAr: "تركيب الأقمار الصناعية", icon: "fas fa-satellite", color: "#6366f1" },
  { name: "Internet Setup", nameAr: "إعداد الإنترنت", icon: "fas fa-wifi", color: "#3b82f6" },
  { name: "Phone Repair", nameAr: "إصلاح الهواتف", icon: "fas fa-mobile-alt", color: "#1f2937" },
  { name: "Computer Repair", nameAr: "إصلاح الحاسوب", icon: "fas fa-laptop", color: "#6b7280" },
  { name: "Interior Design", nameAr: "التصميم الداخلي", icon: "fas fa-paint-roller", color: "#ec4899" },
  { name: "Event Planning", nameAr: "تنظيم الفعاليات", icon: "fas fa-calendar-alt", color: "#f59e0b" },
  { name: "Photography", nameAr: "التصوير", icon: "fas fa-camera", color: "#1f2937" },
  { name: "Catering", nameAr: "الطعام والشراب", icon: "fas fa-utensils", color: "#4caf50" },
  { name: "Delivery", nameAr: "التوصيل", icon: "fas fa-shipping-fast", color: "#f97316" }
];

const providers: Omit<schema.ServiceProvider, 'id'>[] = [
  {
    name: "Ahmed Al-Baghdadi",
    profession: "AC Specialist",
    professionAr: "أخصائي تكييف",
    bio: "Professional AC technician with 10+ years experience in installation, repair, and maintenance.",
    bioAr: "فني تكييف محترف مع أكثر من 10 سنوات خبرة في التركيب والإصلاح والصيانة.",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    rating: 4.8,
    reviewCount: 127,
    phone: "+964 770 123 4567",
    email: "ahmed.ac@worktok.org",
    cityId: 1,
    categoryIds: [1],
    services: ["AC Installation", "AC Repair", "AC Maintenance", "Duct Cleaning"],
    servicesAr: ["تركيب التكييف", "إصلاح التكييف", "صيانة التكييف", "تنظيف المجاري"],
    experienceYears: 10,
    priceRange: "25,000 - 75,000 IQD",
    availability: "Available",
    portfolio: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&h=200&fit=crop",
      "https://images.unsplash.com/photo-1562808240-45e0f0b83fe4?w=300&h=200&fit=crop"
    ],
    isVerified: true,
    languages: ["Arabic", "English"],
    workingHours: "8:00 AM - 6:00 PM"
  },
  {
    name: "Fatima Hassan",
    profession: "Professional Cleaner",
    professionAr: "منظفة محترفة",
    bio: "Expert in residential and commercial cleaning with eco-friendly products.",
    bioAr: "خبيرة في التنظيف السكني والتجاري باستخدام منتجات صديقة للبيئة.",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b77c?w=150&h=150&fit=crop&crop=face",
    rating: 4.9,
    reviewCount: 89,
    phone: "+964 771 987 6543",
    email: "fatima.clean@worktok.org",
    cityId: 2,
    categoryIds: [3],
    services: ["Deep Cleaning", "Regular Cleaning", "Move-in/out Cleaning", "Office Cleaning"],
    servicesAr: ["تنظيف عميق", "تنظيف منتظم", "تنظيف الانتقال", "تنظيف المكاتب"],
    experienceYears: 8,
    priceRange: "15,000 - 50,000 IQD",
    availability: "Available",
    portfolio: [
      "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=300&h=200&fit=crop",
      "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=300&h=200&fit=crop"
    ],
    isVerified: true,
    languages: ["Arabic", "English"],
    workingHours: "7:00 AM - 4:00 PM"
  },
  {
    name: "Omar Al-Najafi",
    profession: "Master Electrician",
    professionAr: "كهربائي رئيسي",
    bio: "Licensed electrician specializing in residential and commercial electrical work.",
    bioAr: "كهربائي مرخص متخصص في الأعمال الكهربائية السكنية والتجارية.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    rating: 4.7,
    reviewCount: 156,
    phone: "+964 772 456 7890",
    email: "omar.electric@worktok.org",
    cityId: 3,
    categoryIds: [6],
    services: ["Wiring", "Panel Upgrades", "Lighting Installation", "Emergency Repairs"],
    servicesAr: ["أسلاك", "ترقية اللوحات", "تركيب الإضاءة", "إصلاحات الطوارئ"],
    experienceYears: 15,
    priceRange: "30,000 - 100,000 IQD",
    availability: "Available",
    portfolio: [
      "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=300&h=200&fit=crop",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&h=200&fit=crop"
    ],
    isVerified: true,
    languages: ["Arabic"],
    workingHours: "8:00 AM - 5:00 PM"
  },
  {
    name: "Kareem Al-Basri",
    profession: "Master Plumber",
    professionAr: "سباك رئيسي",
    bio: "Expert plumber with 12 years experience in all plumbing services.",
    bioAr: "سباك خبير مع 12 سنة خبرة في جميع خدمات السباكة.",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face",
    rating: 4.6,
    reviewCount: 98,
    phone: "+964 773 111 2222",
    email: "kareem.plumber@worktok.org",
    cityId: 1,
    categoryIds: [2],
    services: ["Pipe Repair", "Drain Cleaning", "Faucet Installation", "Water Heater Service"],
    servicesAr: ["إصلاح الأنابيب", "تنظيف المجاري", "تركيب الحنفيات", "خدمة سخان المياه"],
    experienceYears: 12,
    priceRange: "20,000 - 80,000 IQD",
    availability: "Available",
    portfolio: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&h=200&fit=crop"
    ],
    isVerified: true,
    languages: ["Arabic", "English"],
    workingHours: "7:00 AM - 5:00 PM"
  },
  {
    name: "Layla Mohammed",
    profession: "Interior Designer",
    professionAr: "مصممة داخلية",
    bio: "Creative interior designer specializing in modern and traditional Iraqi styles.",
    bioAr: "مصممة داخلية مبدعة متخصصة في الأنماط العراقية الحديثة والتقليدية.",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    rating: 4.9,
    reviewCount: 76,
    phone: "+964 774 333 4444",
    email: "layla.design@worktok.org",
    cityId: 1,
    categoryIds: [26],
    services: ["Room Design", "Color Consultation", "Furniture Selection", "Space Planning"],
    servicesAr: ["تصميم الغرف", "استشارة الألوان", "اختيار الأثاث", "تخطيط المساحة"],
    experienceYears: 7,
    priceRange: "50,000 - 200,000 IQD",
    availability: "Available",
    portfolio: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=300&h=200&fit=crop"
    ],
    isVerified: true,
    languages: ["Arabic", "English"],
    workingHours: "9:00 AM - 6:00 PM"
  },
  {
    name: "Hassan Al-Karkhi",
    profession: "Roofing Specialist",
    professionAr: "أخصائي تسقيف",
    bio: "Professional roofer with expertise in traditional and modern roofing systems.",
    bioAr: "سقاف محترف مع خبرة في أنظمة التسقيف التقليدية والحديثة.",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    rating: 4.7,
    reviewCount: 114,
    phone: "+964 775 555 6666",
    email: "hassan.roof@worktok.org",
    cityId: 2,
    categoryIds: [9],
    services: ["Roof Repair", "New Installation", "Waterproofing", "Gutter Installation"],
    servicesAr: ["إصلاح السقف", "تركيب جديد", "عزل المياه", "تركيب المزاريب"],
    experienceYears: 9,
    priceRange: "40,000 - 150,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic"],
    workingHours: "6:00 AM - 4:00 PM"
  },
  {
    name: "Nour Al-Deen",
    profession: "Carpenter",
    professionAr: "نجار",
    bio: "Skilled carpenter specializing in custom furniture and home improvements.",
    bioAr: "نجار ماهر متخصص في الأثاث المخصص وتحسينات المنزل.",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=face",
    rating: 4.8,
    reviewCount: 132,
    phone: "+964 776 777 8888",
    email: "nour.carpenter@worktok.org",
    cityId: 3,
    categoryIds: [5],
    services: ["Custom Furniture", "Cabinet Installation", "Door Repair", "Shelving"],
    servicesAr: ["أثاث مخصص", "تركيب الخزائن", "إصلاح الأبواب", "الرفوف"],
    experienceYears: 11,
    priceRange: "30,000 - 120,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic", "Kurdish"],
    workingHours: "8:00 AM - 6:00 PM"
  },
  {
    name: "Zeinab Al-Fallujah",
    profession: "Painter",
    professionAr: "دهانة",
    bio: "Professional painter with expertise in residential and commercial painting.",
    bioAr: "دهانة محترفة مع خبرة في الدهان السكني والتجاري.",
    avatar: "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=150&h=150&fit=crop&crop=face",
    rating: 4.6,
    reviewCount: 87,
    phone: "+964 777 999 0000",
    email: "zeinab.painter@worktok.org",
    cityId: 4,
    categoryIds: [4],
    services: ["Interior Painting", "Exterior Painting", "Wallpaper Installation", "Texture Work"],
    servicesAr: ["دهان داخلي", "دهان خارجي", "تركيب ورق الجدران", "أعمال النسيج"],
    experienceYears: 6,
    priceRange: "25,000 - 90,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic"],
    workingHours: "7:00 AM - 5:00 PM"
  },
  {
    name: "Ali Al-Mosul",
    profession: "Welder",
    professionAr: "لحام",
    bio: "Expert welder specializing in structural and decorative metalwork.",
    bioAr: "لحام خبير متخصص في الأعمال المعدنية الهيكلية والزخرفية.",
    avatar: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=150&h=150&fit=crop&crop=face",
    rating: 4.9,
    reviewCount: 145,
    phone: "+964 778 111 2223",
    email: "ali.welder@worktok.org",
    cityId: 5,
    categoryIds: [12],
    services: ["Structural Welding", "Gate Repair", "Metal Fabrication", "Pipe Welding"],
    servicesAr: ["لحام هيكلي", "إصلاح البوابات", "تصنيع المعادن", "لحام الأنابيب"],
    experienceYears: 14,
    priceRange: "35,000 - 110,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic", "Kurdish"],
    workingHours: "8:00 AM - 5:00 PM"
  },
  {
    name: "Maryam Al-Kut",
    profession: "Event Planner",
    professionAr: "منظمة فعاليات",
    bio: "Professional event planner specializing in weddings and corporate events.",
    bioAr: "منظمة فعاليات محترفة متخصصة في حفلات الزفاف والفعاليات المؤسسية.",
    avatar: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=150&h=150&fit=crop&crop=face",
    rating: 4.8,
    reviewCount: 93,
    phone: "+964 779 333 4445",
    email: "maryam.events@worktok.org",
    cityId: 1,
    categoryIds: [27],
    services: ["Wedding Planning", "Corporate Events", "Birthday Parties", "Decoration"],
    servicesAr: ["تخطيط الزفاف", "فعاليات الشركات", "حفلات أعياد الميلاد", "الديكور"],
    experienceYears: 5,
    priceRange: "100,000 - 500,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic", "English"],
    workingHours: "9:00 AM - 7:00 PM"
  },
  {
    name: "Saad Al-Hillah",
    profession: "Security Systems Expert",
    professionAr: "خبير أنظمة أمنية",
    bio: "Professional security systems installer with modern technology expertise.",
    bioAr: "مثبت أنظمة أمنية محترف مع خبرة في التكنولوجيا الحديثة.",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    rating: 4.7,
    reviewCount: 108,
    phone: "+964 770 555 6667",
    email: "saad.security@worktok.org",
    cityId: 2,
    categoryIds: [15],
    services: ["Camera Installation", "Alarm Systems", "Access Control", "Smart Home Security"],
    servicesAr: ["تركيب الكاميرات", "أنظمة الإنذار", "التحكم بالوصول", "أمان المنزل الذكي"],
    experienceYears: 8,
    priceRange: "50,000 - 200,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic", "English"],
    workingHours: "9:00 AM - 6:00 PM"
  },
  {
    name: "Dina Al-Ramadi",
    profession: "Photographer",
    professionAr: "مصورة",
    bio: "Professional photographer specializing in events, portraits, and commercial photography.",
    bioAr: "مصورة محترفة متخصصة في الفعاليات والبورتريه والتصوير التجاري.",
    avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face",
    rating: 4.9,
    reviewCount: 156,
    phone: "+964 771 777 8889",
    email: "dina.photo@worktok.org",
    cityId: 1,
    categoryIds: [28],
    services: ["Wedding Photography", "Event Photography", "Portrait Sessions", "Product Photography"],
    servicesAr: ["تصوير الزفاف", "تصوير الفعاليات", "جلسات البورتريه", "تصوير المنتجات"],
    experienceYears: 6,
    priceRange: "75,000 - 300,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic", "English"],
    workingHours: "10:00 AM - 8:00 PM"
  },
  {
    name: "Khalid Al-Anbar",
    profession: "Appliance Repair Technician",
    professionAr: "فني إصلاح الأجهزة",
    bio: "Expert technician in home appliance repair and maintenance.",
    bioAr: "فني خبير في إصلاح وصيانة الأجهزة المنزلية.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    rating: 4.6,
    reviewCount: 92,
    phone: "+964 772 999 0001",
    email: "khalid.appliance@worktok.org",
    cityId: 3,
    categoryIds: [17],
    services: ["Washing Machine Repair", "Refrigerator Service", "Oven Repair", "Dishwasher Fix"],
    servicesAr: ["إصلاح الغسالة", "خدمة الثلاجة", "إصلاح الفرن", "إصلاح غسالة الصحون"],
    experienceYears: 9,
    priceRange: "20,000 - 70,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic"],
    workingHours: "8:00 AM - 6:00 PM"
  },
  {
    name: "Rana Al-Sulaymaniyah",
    profession: "Gardener",
    professionAr: "بستانية",
    bio: "Professional gardener with expertise in landscape design and plant care.",
    bioAr: "بستانية محترفة مع خبرة في تصميم المناظر الطبيعية ورعاية النباتات.",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    rating: 4.8,
    reviewCount: 74,
    phone: "+964 773 777 8890",
    email: "rana.garden@worktok.org",
    cityId: 4,
    categoryIds: [7],
    services: ["Garden Design", "Tree Pruning", "Irrigation Systems", "Plant Installation"],
    servicesAr: ["تصميم الحديقة", "تقليم الأشجار", "أنظمة الري", "زراعة النباتات"],
    experienceYears: 7,
    priceRange: "30,000 - 100,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic", "Kurdish", "English"],
    workingHours: "6:00 AM - 3:00 PM"
  },
  {
    name: "Mohammed Al-Diwaniyah",
    profession: "Moving Specialist",
    professionAr: "أخصائي نقل",
    bio: "Professional moving service with careful handling and timely delivery.",
    bioAr: "خدمة نقل محترفة مع المناولة الحذرة والتسليم في الوقت المحدد.",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    rating: 4.5,
    reviewCount: 118,
    phone: "+964 774 111 2224",
    email: "mohammed.moving@worktok.org",
    cityId: 5,
    categoryIds: [8],
    services: ["Residential Moving", "Office Relocation", "Packing Services", "Storage Solutions"],
    servicesAr: ["نقل سكني", "نقل المكاتب", "خدمات التعبئة", "حلول التخزين"],
    experienceYears: 10,
    priceRange: "40,000 - 150,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic"],
    workingHours: "7:00 AM - 6:00 PM"
  },
  {
    name: "Salma Al-Zawraa",
    profession: "TV Mounting Specialist",
    professionAr: "أخصائية تركيب التلفزيون",
    bio: "Expert in TV mounting and home entertainment system setup.",
    bioAr: "خبيرة في تركيب التلفزيون وإعداد نظام الترفيه المنزلي.",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b77c?w=150&h=150&fit=crop&crop=face",
    rating: 4.7,
    reviewCount: 85,
    phone: "+964 775 333 4446",
    email: "salma.tv@worktok.org",
    cityId: 1,
    categoryIds: [19],
    services: ["TV Wall Mount", "Cable Management", "Surround Sound Setup", "Gaming Console Install"],
    servicesAr: ["تثبيت التلفزيون على الحائط", "إدارة الكابلات", "إعداد الصوت المحيطي", "تثبيت منصة الألعاب"],
    experienceYears: 4,
    priceRange: "25,000 - 80,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic", "English"],
    workingHours: "9:00 AM - 6:00 PM"
  },
  {
    name: "Yassin Al-Kirkuk",
    profession: "Computer Repair Technician",
    professionAr: "فني إصلاح الحاسوب",
    bio: "Professional computer technician specializing in hardware and software issues.",
    bioAr: "فني حاسوب محترف متخصص في مشاكل الأجهزة والبرمجيات.",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face",
    rating: 4.8,
    reviewCount: 134,
    phone: "+964 776 555 6668",
    email: "yassin.computer@worktok.org",
    cityId: 2,
    categoryIds: [25],
    services: ["Hardware Repair", "Software Installation", "Virus Removal", "Data Recovery"],
    servicesAr: ["إصلاح الأجهزة", "تثبيت البرمجيات", "إزالة الفيروسات", "استعادة البيانات"],
    experienceYears: 8,
    priceRange: "20,000 - 100,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic", "English", "Kurdish"],
    workingHours: "9:00 AM - 7:00 PM"
  },
  {
    name: "Amina Al-Samawah",
    profession: "Tile Installer",
    professionAr: "مثبتة البلاط",
    bio: "Expert tile installer with precision in ceramic, porcelain, and natural stone.",
    bioAr: "مثبتة بلاط خبيرة مع دقة في السيراميك والبورسلين والحجر الطبيعي.",
    avatar: "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=150&h=150&fit=crop&crop=face",
    rating: 4.9,
    reviewCount: 97,
    phone: "+964 777 777 8891",
    email: "amina.tile@worktok.org",
    cityId: 3,
    categoryIds: [11],
    services: ["Ceramic Tile", "Porcelain Installation", "Natural Stone", "Bathroom Tiling"],
    servicesAr: ["بلاط السيراميك", "تركيب البورسلين", "الحجر الطبيعي", "بلاط الحمام"],
    experienceYears: 6,
    priceRange: "30,000 - 120,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic"],
    workingHours: "7:00 AM - 4:00 PM"
  },
  {
    name: "Haider Al-Karbala",
    profession: "Satellite Installer",
    professionAr: "مثبت الأقمار الصناعية",
    bio: "Professional satellite installation and maintenance specialist.",
    bioAr: "أخصائي تركيب وصيانة الأقمار الصناعية المحترف.",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=face",
    rating: 4.6,
    reviewCount: 102,
    phone: "+964 778 999 0002",```tool_code
email: "haider.satellite@worktok.org",
    cityId: 4,
    categoryIds: [22],
    services: ["Dish Installation", "Signal Optimization", "Receiver Setup", "Maintenance"],
    servicesAr: ["تركيب الطبق", "تحسين الإشارة", "إعداد المستقبل", "الصيانة"],
    experienceYears: 7,
    priceRange: "25,000 - 75,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic"],
    workingHours: "8:00 AM - 5:00 PM"
  },
  {
    name: "Laith Al-Amarah",
    profession: "Pool Maintenance Specialist",
    professionAr: "أخصائي صيانة المسابح",
    bio: "Expert in pool cleaning, chemical balancing, and equipment maintenance.",
    bioAr: "خبير في تنظيف المسابح وتوازن المواد الكيميائية وصيانة المعدات.",
    avatar: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=150&h=150&fit=crop&crop=face",
    rating: 4.8,
    reviewCount: 67,
    phone: "+964 779 111 2225",
    email: "laith.pool@worktok.org",
    cityId: 1,
    categoryIds: [20],
    services: ["Pool Cleaning", "Chemical Balancing", "Equipment Repair", "Seasonal Maintenance"],
    servicesAr: ["تنظيف المسبح", "توازن المواد الكيميائية", "إصلاح المعدات", "الصيانة الموسمية"],
    experienceYears: 5,
    priceRange: "40,000 - 120,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic", "English"],
    workingHours: "7:00 AM - 4:00 PM"
  },
  {
    name: "Israa Al-Tikrit",
    profession: "Pest Control Specialist",
    professionAr: "أخصائية مكافحة الآفات",
    bio: "Professional pest control with eco-friendly and effective solutions.",
    bioAr: "مكافحة الآفات المحترفة مع الحلول الصديقة للبيئة والفعالة.",
    avatar: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=150&h=150&fit=crop&crop=face",
    rating: 4.7,
    reviewCount: 89,
    phone: "+964 770 333 4447",
    email: "israa.pest@worktok.org",
    cityId: 2,
    categoryIds: [16],
    services: ["Insect Control", "Rodent Removal", "Termite Treatment", "Prevention Programs"],
    servicesAr: ["مكافحة الحشرات", "إزالة القوارض", "علاج النمل الأبيض", "برامج الوقاية"],
    experienceYears: 6,
    priceRange: "30,000 - 100,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic"],
    workingHours: "8:00 AM - 5:00 PM"
  },
  {
    name: "Mustafa Al-Fallujah",
    profession: "Solar Panel Installer",
    professionAr: "مثبت الألواح الشمسية",
    bio: "Certified solar panel installer promoting sustainable energy solutions.",
    bioAr: "مثبت ألواح شمسية معتمد يروج لحلول الطاقة المستدامة.",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    rating: 4.9,
    reviewCount: 78,
    phone: "+964 771 555 6669",
    email: "mustafa.solar@worktok.org",
    cityId: 3,
    categoryIds: [21],
    services: ["Panel Installation", "System Design", "Battery Setup", "Maintenance"],
    servicesAr: ["تركيب الألواح", "تصميم النظام", "إعداد البطارية", "الصيانة"],
    experienceYears: 4,
    priceRange: "200,000 - 800,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic", "English"],
    workingHours: "7:00 AM - 5:00 PM"
  },
  {
    name: "Hiba Al-Hilla",
    profession: "Glass Work Specialist",
    professionAr: "أخصائية أعمال الزجاج",
    bio: "Expert in glass installation, repair, and custom glass solutions.",
    bioAr: "خبيرة في تركيب الزجاج والإصلاح وحلول الزجاج المخصصة.",
    avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face",
    rating: 4.6,
    reviewCount: 91,
    phone: "+964 772 777 8892",
    email: "hiba.glass@worktok.org",
    cityId: 4,
    categoryIds: [13],
    services: ["Window Repair", "Mirror Installation", "Glass Doors", "Shower Enclosures"],
    servicesAr: ["إصلاح النوافذ", "تركيب المرايا", "أبواب زجاجية", "حاويات الدش"],
    experienceYears: 8,
    priceRange: "25,000 - 150,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic"],
    workingHours: "8:00 AM - 4:00 PM"
  },
  {
    name: "Qasim Al-Nasiriyah",
    profession: "Masonry Specialist",
    professionAr: "أخصائي البناء",
    bio: "Professional mason specializing in brickwork, stonework, and concrete.",
    bioAr: "بناء محترف متخصص في أعمال الطوب والحجر والخرسانة.",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    rating: 4.8,
    reviewCount: 125,
    phone: "+964 773 999 0003",
    email: "qasim.masonry@worktok.org",
    cityId: 5,
    categoryIds: [14],
    services: ["Brick Work", "Stone Installation", "Concrete Repair", "Foundation Work"],
    servicesAr: ["أعمال الطوب", "تركيب الحجر", "إصلاح الخرسانة", "أعمال الأساس"],
    experienceYears: 13,
    priceRange: "35,000 - 200,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic"],
    workingHours: "6:00 AM - 4:00 PM"
  },
  {
    name: "Eman Al-Ramadi",
    profession: "Furniture Assembly Specialist",
    professionAr: "أخصائية تجميع الأثاث",
    bio: "Expert in furniture assembly and installation for home and office.",
    bioAr: "خبيرة في تجميع وتركيب الأثاث للمنزل والمكتب.",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    rating: 4.7,
    reviewCount: 103,
    phone: "+964 774 333 4448",
    email: "eman.furniture@worktok.org",
    cityId: 1,
    categoryIds: [18],
    services: ["IKEA Assembly", "Office Furniture", "Bedroom Sets", "Dining Room"],
    servicesAr: ["تجميع ايكيا", "أثاث المكتب", "مجموعات غرف النوم", "غرفة الطعام"],
    experienceYears: 3,
    priceRange: "15,000 - 60,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic", "English"],
    workingHours: "9:00 AM - 6:00 PM"
  },
  {
    name: "Tariq Al-Baqubah",
    profession: "Phone Repair Technician",
    professionAr: "فني إصلاح الهواتف",
    bio: "Mobile phone repair specialist for all brands and models.",
    bioAr: "أخصائي إصلاح الهواتف المحمولة لجميع العلامات التجارية والموديلات.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    rating: 4.5,
    reviewCount: 156,
    phone: "+964 775 777 8893",
    email: "tariq.phone@worktok.org",
    cityId: 2,
    categoryIds: [24],
    services: ["Screen Repair", "Battery Replacement", "Water Damage", "Software Issues"],
    servicesAr: ["إصلاح الشاشة", "استبدال البطارية", "أضرار المياه", "مشاكل البرمجيات"],
    experienceYears: 5,
    priceRange: "10,000 - 50,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic", "English"],
    workingHours: "9:00 AM - 8:00 PM"
  },
  {
    name: "Dalia Al-Kut",
    profession: "Internet Setup Specialist",
    professionAr: "أخصائية إعداد الإنترنت",
    bio: "Professional internet and network setup specialist for homes and businesses.",
    bioAr: "أخصائية إعداد الإنترنت والشبكات المحترفة للمنازل والشركات.",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b77c?w=150&h=150&fit=crop&crop=face",
    rating: 4.8,
    reviewCount: 87,
    phone: "+964 776 111 2226",
    email: "dalia.internet@worktok.org",
    cityId: 3,
    categoryIds: [23],
    services: ["WiFi Setup", "Router Configuration", "Network Troubleshooting", "Cable Installation"],
    servicesAr: ["إعداد الواي فاي", "تكوين الراوتر", "استكشاف أخطاء الشبكة", "تركيب الكابلات"],
    experienceYears: 4,
    priceRange: "20,000 - 80,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic", "English"],
    workingHours: "9:00 AM - 6:00 PM"
  },
  {
    name: "Bassam Al-Samarra",
    profession: "Flooring Specialist",
    professionAr: "أخصائي الأرضيات",
    bio: "Expert in all types of flooring installation and repair.",
    bioAr: "خبير في جميع أنواع تركيب وإصلاح الأرضيات.",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=face",
    rating: 4.7,
    reviewCount: 119,
    phone: "+964 777 333 4449",
    email: "bassam.flooring@worktok.org",
    cityId: 4,
    categoryIds: [10],
    services: ["Laminate Flooring", "Hardwood Installation", "Vinyl Flooring", "Floor Repair"],
    servicesAr: ["أرضيات الخشب المضغوط", "تركيب الخشب الصلب", "أرضيات الفينيل", "إصلاح الأرضيات"],
    experienceYears: 9,
    priceRange: "40,000 - 180,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic"],
    workingHours: "7:00 AM - 5:00 PM"
  },
  {
    name: "Lubna Al-Dahuk",
    profession: "Catering Specialist",
    professionAr: "أخصائية الطعام والشراب",
    bio: "Professional catering service for events and special occasions.",
    bioAr: "خدمة طعام محترفة للفعاليات والمناسبات الخاصة.",
    avatar: "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=150&h=150&fit=crop&crop=face",
    rating: 4.9,
    reviewCount: 142,
    phone: "+964 778 555 6670",
    email: "lubna.catering@worktok.org",
    cityId: 5,
    categoryIds: [29],
    services: ["Wedding Catering", "Corporate Events", "Birthday Parties", "Traditional Iraqi Food"],
    servicesAr: ["تقديم طعام الزفاف", "فعاليات الشركات", "حفلات أعياد الميلاد", "الطعام العراقي التقليدي"],
    experienceYears: 8,
    priceRange: "50,000 - 300,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic", "Kurdish"],
    workingHours: "8:00 AM - 10:00 PM"
  },
  {
    name: "Rami Al-Wasit",
    profession: "Delivery Specialist",
    professionAr: "أخصائي التوصيل",
    bio: "Fast and reliable delivery service for packages and documents.",
    bioAr: "خدمة توصيل سريعة وموثوقة للطرود والوثائق.",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=face",
    rating: 4.6,
    reviewCount: 98,
    phone: "+964 779 777 8894",
    email: "rami.delivery@worktok.org",
    cityId: 1,
    categoryIds: [30],
    services: ["Same Day Delivery", "Express Delivery", "Document Delivery", "Package Delivery"],
    servicesAr: ["التوصيل في نفس اليوم", "التوصيل السريع", "توصيل الوثائق", "توصيل الطرود"],
    experienceYears: 6,
    priceRange: "5,000 - 25,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic"],
    workingHours: "6:00 AM - 10:00 PM"
  },
   {
    name: "Sara Al-Najaf",
    profession: "Housekeeping",
    professionAr: "خدمة تنظيف المنازل",
    bio: "Professional housekeeping service for all your needs.",
    bioAr: "خدمة تنظيف المنازل المحترفة لجميع احتياجاتك.",
    avatar: "https://images.unsplash.com/photo-1598214886806-c87b519d42ba?w=150&h=150&fit=crop&crop=face",
    rating: 4.7,
    reviewCount: 112,
    phone: "+964 770 987 6543",
    email: "sara.housekeeping@worktok.org",
    cityId: 2,
    categoryIds: [3],
    services: ["Regular Cleaning", "Deep Cleaning", "Laundry", "Ironing"],
    servicesAr: ["تنظيف منتظم", "تنظيف عميق", "غسيل الملابس", "كي الملابس"],
    experienceYears: 7,
    priceRange: "15,000 - 60,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic", "English"],
    workingHours: "8:00 AM - 5:00 PM"
  },
  {
    name: "Jasim Al-Basra",
    profession: "Landscaping",
    professionAr: "تنسيق الحدائق",
    bio: "Expert landscaping services for gardens and outdoor spaces.",
    bioAr: "خدمات تنسيق الحدائق الخبيرة للحدائق والمساحات الخارجية.",
    avatar: "https://images.unsplash.com/photo-1587324174844-647c61054112?w=150&h=150&fit=crop&crop=face",
    rating: 4.9,
    reviewCount: 135,
    phone: "+964 771 123 4567",
    email: "jasim.landscaping@worktok.org",
    cityId: 3,
    categoryIds: [7],
    services: ["Garden Design", "Lawn Care", "Planting", "Irrigation"],
    servicesAr: ["تصميم الحدائق", "العناية بالعشب", "زراعة", "الري"],
    experienceYears: 10,
    priceRange: "30,000 - 120,000 IQD",
    availability: "Available",
    portfolio: [],
    isVerified: true,
    languages: ["Arabic", "English"],
    workingHours: "7:00 AM - 4:00 PM"
  },
  {
        name: "Ali Al-Baghdadi",
        profession: "AC Technician",
        professionAr: "فني تكييف",
        bio: "Your trusted AC technician for installation and maintenance.",
        bioAr: "فني تكييف موثوق به للتركيب والصيانة.",
        avatar: "https://images.unsplash.com/photo-1617168736884-270302160821?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YWN8ZW58MHx8MHx8MTY5NzQyMzc0NHww&w=150&h=150&fit=crop",
        rating: 4.5,
        reviewCount: 123,
        phone: "+9647501234567",
        email: "ali.ac@example.com",
        cityId: 1,
        categoryIds: [1],
        services: ["AC Installation", "AC Repair", "AC Maintenance"],
        servicesAr: ["تركيب تكييف", "إصلاح تكييف", "صيانة تكييف"],
        experienceYears: 7,
        priceRange: "20,000 - 50,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic", "English"],
        workingHours: "9:00 AM - 6:00 PM"
    },
    {
        name: "Huda Al-Basri",
        profession: "Plumber",
        professionAr: "سباكة",
        bio: "Reliable plumbing services for all your needs.",
        bioAr: "خدمات سباكة موثوقة لجميع احتياجاتك.",
        avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fHBsdW1iZXJ8ZW58MHx8MHx8MTY5NzQyMzc4OXww&w=150&h=150&fit=crop",
        rating: 4.8,
        reviewCount: 98,
        phone: "+9647719876543",
        email: "huda.plumber@example.com",
        cityId: 2,
        categoryIds: [2],
        services: ["Pipe Repair", "Faucet Installation", "Drain Cleaning"],
        servicesAr: ["إصلاح الأنابيب", "تركيب الحنفيات", "تسليك المجاري"],
        experienceYears: 5,
        priceRange: "15,000 - 40,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic"],
        workingHours: "8:00 AM - 5:00 PM"
    },
    {
        name: "Zaid Al-Karkhi",
        profession: "Electrician",
        professionAr: "كهربائي",
        bio: "Your trusted electrician for any electrical issues.",
        bioAr: "كهربائي موثوق به لأي مشاكل كهربائية.",
        avatar: "https://images.unsplash.com/photo-1513161455071-1035590f9678?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGVsZWN0cmljaWFufGVufDB8fDB8fDE2OTc0MjM4MDF8MA&w=150&h=150&fit=crop",
        rating: 4.6,
        reviewCount: 112,
        phone: "+9647901122333",
        email: "zaid.electric@example.com",
        cityId: 3,
        categoryIds: [6],
        services: ["Wiring", "Lighting Installation", "Panel Upgrades"],
        servicesAr: ["تمديدات كهربائية", "تركيب الإضاءة", "ترقية اللوحات"],
        experienceYears: 8,
        priceRange: "25,000 - 60,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic"],
        workingHours: "7:00 AM - 4:00 PM"
    },
    {
        name: "Lina Al-Ramadi",
        profession: "Carpenter",
        professionAr: "نجارة",
        bio: "Professional carpentry services for your home.",
        bioAr: "خدمات نجارة محترفة لمنزلك.",
        avatar: "https://images.unsplash.com/photo-1551882547-68466c2d931c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGNhcnBlbnRlcnxlbnwwfHwwfHx8MTY5NzQyMzgzNXww&w=150&h=150&fit=crop",
        rating: 4.9,
        reviewCount: 87,
        phone: "+9647723456789",
        email: "lina.carpenter@example.com",
        cityId: 4,
        categoryIds: [5],
        services: ["Furniture Repair", "Custom Cabinets", "Door Installation"],
        servicesAr: ["إصلاح الأثاث", "خزائن مخصصة", "تركيب الأبواب"],
        experienceYears: 6,
        priceRange: "20,000 - 50,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic", "English"],
        workingHours: "8:00 AM - 5:00 PM"
    },
    {
        name: "Samer Al-Sulaymaniyah",
        profession: "Painter",
        professionAr: "رسام",
        bio: "Transforming homes with professional painting services.",
        bioAr: "تحويل المنازل بخدمات الدهان الاحترافية.",
        avatar: "https://images.unsplash.com/photo-1606854533554-01c93e24ffb0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NzJ8fHBhaW50ZXJ8ZW58MHx8MHx8MTY5NzQyMzg2OXww&w=150&h=150&fit=crop",
        rating: 4.7,
        reviewCount: 101,
        phone: "+9647514567890",
        email: "samer.painter@example.com",
        cityId: 5,
        categoryIds: [4],
        services: ["Interior Painting", "Exterior Painting", "Wallpaper Installation"],
        servicesAr: ["الدهان الداخلي", "الدهان الخارجي", "تركيب ورق الحائط"],
        experienceYears: 9,
        priceRange: "25,000 - 55,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic", "Kurdish"],
        workingHours: "9:00 AM - 6:00 PM"
    },
    {
        name: "Nadia Al-Anbar",
        profession: "Cleaner",
        professionAr: "منظفة",
        bio: "Reliable and thorough cleaning services for your home.",
        bioAr: "خدمات تنظيف موثوقة وشاملة لمنزلك.",
        avatar: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGNsZWFuZXJ8ZW58MHx8MHx8MTY5NzQyMzkxNXww&w=150&h=150&fit=crop",
        rating: 4.8,
        reviewCount: 92,
        phone: "+9647735678901",
        email: "nadia.cleaner@example.com",
        cityId: 1,
        categoryIds: [3],
        services: ["Deep Cleaning", "Regular Cleaning", "Office Cleaning"],
        servicesAr: ["تنظيف عميق", "تنظيف منتظم", "تنظيف المكاتب"],
        experienceYears: 7,
        priceRange: "15,000 - 45,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic"],
        workingHours: "10:00 AM - 7:00 PM"
    },
    {
        name: "Kadir Al-Mosul",
        profession: "Gardener",
        professionAr: "بستاني",
        bio: "Creating beautiful outdoor spaces with expert gardening services.",
        bioAr: "خلق مساحات خارجية جميلة مع خدمات البستنة الخبيرة.",
        avatar: "https://images.unsplash.com/photo-1603872810140-c118ba509271?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z2FyZGVuZXJ8ZW58MHx8MHx8MTY5NzQyMzk0OXww&w=150&h=150&fit=crop",
        rating: 4.6,
        reviewCount: 78,
        phone: "+9647506789012",
        email: "kadir.gardener@example.com",
        cityId: 2,
        categoryIds: [7],
        services: ["Lawn Care", "Planting", "Garden Design"],
        servicesAr: ["العناية بالعشب", "زراعة", "تصميم الحدائق"],
        experienceYears: 11,
        priceRange: "30,000 - 60,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic", "Kurdish"],
        workingHours: "6:00 AM - 3:00 PM"
    },
    {
        name: "Layla Al-Diwaniyah",
        profession: "Moving Service",
        professionAr: "خدمة نقل",
        bio: "Reliable moving services for stress-free relocation.",
        bioAr: "خدمات نقل موثوقة لنقل خالٍ من الإجهاد.",
        avatar: "https://images.unsplash.com/photo-1616878508339-5ddde630433b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8bW92aW5nJTIwc2VydmljZXxlbnwwfHwwfHx8MTY5NzQyMzk4NXww&w=150&h=150&fit=crop",
        rating: 4.9,
        reviewCount: 105,
        phone: "+9647717890123",
        email: "layla.moving@example.com",
        cityId: 3,
        categoryIds: [8],
        services: ["Packing", "Loading", "Transportation"],
        servicesAr: ["تعبئة", "تحميل", "نقل"],
        experienceYears: 5,
        priceRange: "40,000 - 70,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic"],
        workingHours: "7:00 AM - 4:00 PM"
    },
    {
        name: "Riyadh Al-Fallujah",
        profession: "Roofing Specialist",
        professionAr: "أخصائي تسقيف",
        bio: "Expert roofing services for a secure home.",
        bioAr: "خدمات تسقيف خبيرة لمنزل آمن.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.7,
        reviewCount: 81,
        phone: "+9647508901234",
        email: "riyadh.roofing@example.com",
        cityId: 4,
        categoryIds: [9],
        services: ["Roof Repair", "Roof Installation", "Waterproofing"],
        servicesAr: ["إصلاح السقف", "تركيب السقف", "عزل المياه"],
        experienceYears: 10,
        priceRange: "35,000 - 65,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic"],
        workingHours: "8:00 AM - 5:00 PM"
    },
    {
        name: "Abeer Al-Hillah",
        profession: "Flooring Expert",
        professionAr: "خبير الأرضيات",
        bio: "High-quality flooring services to enhance your home's beauty.",
        bioAr: "خدمات أرضيات عالية الجودة لتعزيز جمال منزلك.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZpbmd8ZW58MHx8MHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.5,
        reviewCount: 94,
        phone: "+9647729012345",
        email: "abeer.flooring@example.com",
        cityId: 5,
        categoryIds: [10],
        services: ["Tile Installation", "Wood Flooring", "Carpet Installation"],
        servicesAr: ["تركيب البلاط", "الأرضيات الخشبية", "تركيب السجاد"],
        experienceYears: 6,
        priceRange: "45,000 - 75,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic", "English"],
        workingHours: "9:00 AM - 6:00 PM"
    },
    {
        name: "Jamal Al-Wasit",
        profession: "Tile Installer",
        professionAr: "مركب بلاط",
        bio: "Precise and professional tile installation for homes and businesses.",
        bioAr: "تركيب بلاط دقيق واحترافي للمنازل والشركات.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.8,
        reviewCount: 108,
        phone: "+9647510123456",
        email: "jamal.tile@example.com",
        cityId: 1,
        categoryIds: [11],
        services: ["Bathroom Tiling", "Kitchen Tiling", "Floor Tiling"],
        servicesAr: ["تبليط الحمامات", "تبليط المطابخ", "تبليط الأرضيات"],
        experienceYears: 8,
        priceRange: "20,000 - 50,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic"],
        workingHours: "7:00 AM - 4:00 PM"
    },
    {
        name: "Hanan Al-Karbala",
        profession: "Welding Specialist",
        professionAr: "أخصائية لحام",
        bio: "Certified welding services for all your metal needs.",
        bioAr: "خدمات لحام معتمدة لجميع احتياجاتك المعدنية.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.6,
        reviewCount: 75,
        phone: "+9647731234567",
        email: "hanan.welding@example.com",
        cityId: 2,
        categoryIds: [12],
        services: ["Metal Fabrication", "Pipe Welding", "Structural Welding"],
        servicesAr: ["تصنيع المعادن", "لحام الأنابيب", "لحام الهياكل"],
        experienceYears: 7,
        priceRange: "30,000 - 60,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic", "English"],
        workingHours: "8:00 AM - 5:00 PM"
    },
    {
        name: "Basim Al-Najaf",
        profession: "Glass Expert",
        professionAr: "خبير زجاج",
        bio: "Professional glass installation and repair services.",
        bioAr: "خدمات تركيب وإصلاح الزجاج الاحترافية.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.9,
        reviewCount: 115,
        phone: "+9647512345678",
        email: "basim.glass@example.com",
        cityId: 3,
        categoryIds: [13],
        services: ["Window Repair", "Mirror Installation", "Glass Doors"],
        servicesAr: ["إصلاح النوافذ", "تركيب المرايا", "أبواب زجاجية"],
        experienceYears: 9,
        priceRange: "25,000 - 55,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic"],
        workingHours: "9:00 AM - 6:00 PM"
    },
     {
        name: "Muna Al-Sulaymaniyah",
        profession: "Mason",
        professionAr: "بناء",
        bio: "Skilled in all types of masonry work.",
        bioAr: "مهارة في جميع أنواع أعمال البناء.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.7,
        reviewCount: 88,
        phone: "+9647701234567",
        email: "muna.mason@example.com",
        cityId: 4,
        categoryIds: [14],
        services: ["Bricklaying", "Stone Masonry", "Concrete Work"],
        servicesAr: ["وضع الطوب", "بناء الحجر", "أعمال خرسانية"],
        experienceYears: 10,
        priceRange: "35,000 - 65,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic", "Kurdish"],
        workingHours: "7:00 AM - 4:00 PM"
    },
    {
        name: "Faris Al-Anbar",
        profession: "Security Systems Technician",
        professionAr: "فني أنظمة أمنية",
        bio: "Professional installation and maintenance of security systems.",
        bioAr: "تركيب وصيانة احترافية لأنظمة الأمن.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.8,
        reviewCount: 99,
        phone: "+9647514567890",
        email: "faris.security@example.com",
        cityId: 5,
        categoryIds: [15],
        services: ["Alarm Installation", "Camera Systems", "Access Control"],
        servicesAr: ["تركيب إنذار", "أنظمة الكاميرات", "التحكم في الوصول"],
        experienceYears: 6,
        priceRange: "40,000 - 70,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic"],
        workingHours: "8:00 AM - 5:00 PM"
    },
    {
        name: "Duha Al-Diwaniyah",
        profession: "Pest Controller",
        professionAr: "مكافحة الحشرات",
        bio: "Effective pest control services for your home and business.",
        bioAr: "خدمات فعالة لمكافحة الحشرات لمنزلك وعملك.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.6,
        reviewCount: 102,
        phone: "+9647725678901",
        email: "duha.pestcontrol@example.com",
        cityId: 1,
        categoryIds: [16],
        services: ["Insect Control", "Rodent Control", "Termite Treatment"],
        servicesAr: ["مكافحة الحشرات", "مكافحة القوارض", "معالجة النمل الأبيض"],
        experienceYears: 7,
        priceRange: "20,000 - 50,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic", "English"],
        workingHours: "9:00 AM - 6:00 PM"
    },
    {
        name: "Luay Al-Fallujah",
        profession: "Appliance Repair",
        professionAr: "تصليح أجهزة",
        bio: "Expert in repairing all types of home appliances.",
        bioAr: "خبير في إصلاح جميع أنواع الأجهزة المنزلية.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.9,
        reviewCount: 93,
        phone: "+9647516789012",
        email: "luay.appliancerepair@example.com",
        cityId: 2,
        categoryIds: [17],
        services: ["Washing Machines", "Refrigerators", "Ovens"],
        servicesAr: ["غسالات", "ثلاجات", "أفران"],
        experienceYears: 8,
        priceRange: "25,000 - 55,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic"],
        workingHours: "10:00 AM - 7:00 PM"
    },
     {
        name: "Rasha Al-Kut",
        profession: "Furniture Assembly",
        professionAr: "تجميع أثاث",
        bio: "Professional furniture assembly services.",
        bioAr: "خدمات تجميع الأثاث الاحترافية.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.7,
        reviewCount: 105,
        phone: "+9647737890123",
        email: "rasha.furniture@example.com",
        cityId: 3,
        categoryIds: [18],
        services: ["IKEA Furniture", "Office Furniture", "Home Furniture"],
        servicesAr: ["أثاث ايكيا", "أثاث مكتبي", "أثاث منزلي"],
        experienceYears: 9,
        priceRange: "30,000 - 60,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic"],
        workingHours: "6:00 AM - 3:00 PM"
    },
    {
        name: "Hassan Al-Basra",
        profession: "TV Mounting",
        professionAr: "تركيب تلفزيونات",
        bio: "Expert in safely mounting TVs in your home or office.",
        bioAr: "خبير في تركيب التلفزيونات بأمان في منزلك أو مكتبك.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.8,
        reviewCount: 82,
        phone: "+9647508901234",
        email: "hassan.tvmounting@example.com",
        cityId: 4,
        categoryIds: [19],
        services: ["Wall Mounting", "Cable Management", "Home Theater Setup"],
        servicesAr: ["تركيب على الحائط", "إدارة الكابلات", "إعداد المسرح المنزلي"],
        experienceYears: 5,
        priceRange: "35,000 - 65,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic", "English"],
        workingHours: "7:00 AM - 4:00 PM"
    },
    {
        name: "Amir Al-Wasit",
        profession: "Pool Maintenance",
        professionAr: "صيانة مسابح",
        bio: "Professional pool maintenance and cleaning services.",
        bioAr: "خدمات صيانة وتنظيف المسابح الاحترافية.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.6,
        reviewCount: 110,
        phone: "+9647719012345",
        email: "amir.pool@example.com",
        cityId: 5,
        categoryIds: [20],
        services: ["Pool Cleaning", "Chemical Balancing", "Equipment Repair"],
        servicesAr: ["تنظيف المسبح", "موازنة المواد الكيميائية", "إصلاح المعدات"],
        experienceYears: 6,
        priceRange: "40,000 - 70,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic"],
        workingHours: "8:00 AM - 5:00 PM"
    },
    {
        name: "Suhail Al-Karkh",
        profession: "Solar Panel Installation",
        professionAr: "تركيب ألواح شمسية",
        bio: "Expert in solar panel installation and maintenance.",
        bioAr: "خبير في تركيب وصيانة الألواح الشمسية.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.9,
        reviewCount: 76,
        phone: "+9647510123456",
        email: "suhail.solar@example.com",
        cityId: 1,
        categoryIds: [21],
        services: ["Panel Installation", "System Maintenance", "Energy Consultation"],
        servicesAr: ["تركيب الألواح", "صيانة النظام", "استشارات الطاقة"],
        experienceYears: 7,
        priceRange: "45,000 - 75,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic"],
        workingHours: "9:00 AM - 6:00 PM"
    },
    {
        name: "Nawal Al-Hillah",
        profession: "Satellite Installation",
        professionAr: "تركيب ستلايت",
        bio: "Professional satellite dish installation services.",
        bioAr: "خدمات تركيب أطباق الستلايت الاحترافية.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.7,
        reviewCount: 89,
        phone: "+9647731234567",
        email: "nawal.satellite@example.com",
        cityId: 2,
        categoryIds: [22],
        services: ["Dish Installation", "Signal Setup", "Receiver Configuration"],
        servicesAr: ["تركيب الصحن", "إعداد الإشارة", "تكوين المستقبل"],
        experienceYears: 8,
        priceRange: "20,000 - 50,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic", "English"],
        workingHours: "10:00 AM - 7:00 PM"
    },
    {
        name: "Qusay Al-Ramadi",
        profession: "Internet Technician",
        professionAr: "فني إنترنت",
        bio: "Expert in setting up and troubleshooting internet connections.",
        bioAr: "خبير في إعداد واستكشاف مشاكل اتصالات الإنترنت.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.8,
        reviewCount: 95,
        phone: "+9647512345678",
        email: "qusay.internet@example.com",
        cityId: 3,
        categoryIds: [23],
        services: ["Router Setup", "WiFi Configuration", "Troubleshooting"],
        servicesAr: ["إعداد الراوتر", "تكوين واي فاي", "استكشاف الأخطاء وإصلاحها"],
        experienceYears: 6,
        priceRange: "25,000 - 55,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic"],
        workingHours: "6:00 AM - 3:00 PM"
    },
    {
        name: "Iman Al-Sulaymaniyah",
        profession: "Phone Repair Specialist",
        professionAr: "أخصائية تصليح هواتف",
        bio: "Reliable mobile phone repair services.",
        bioAr: "خدمات موثوقة لتصليح الهواتف المحمولة.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.6,
        reviewCount: 101,
        phone: "+9647733445566",
        email: "iman.phonerepair@example.com",
        cityId: 4,
        categoryIds: [24],
        services: ["Screen Replacement", "Battery Replacement", "Software Fixes"],
        servicesAr: ["استبدال الشاشة", "استبدال البطارية", "إصلاح البرمجيات"],
        experienceYears: 7,
        priceRange: "30,000 - 60,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic", "Kurdish"],
        workingHours: "7:00 AM - 4:00 PM"
    },
    {
        name: "Waleed Al-Fallujah",
        profession: "Computer Repair",
        professionAr: "تصليح حواسيب",
        bio: "Expert computer repair services for all brands and models.",
        bioAr: "خدمات خبير في تصليح الحواسيب لجميع العلامات التجارية والموديلات.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.9,
        reviewCount: 112,
        phone: "+9647504455667",
        email: "waleed.computer@example.com",
        cityId: 5,
        categoryIds: [25],
        services: ["Hardware Repair", "Software Installation", "Virus Removal"],
        servicesAr: ["إصلاح الأجهزة", "تثبيت البرمجيات", "إزالة الفيروسات"],
        experienceYears: 8,
        priceRange: "35,000 - 65,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic"],
        workingHours: "8:00 AM - 5:00 PM"
    },
    {
        name: "Sanaa Al-Kut",
        profession: "Interior Designer",
        professionAr: "مصممة داخلية",
        bio: "Creative interior design services to transform your space.",
        bioAr: "خدمات تصميم داخلي إبداعية لتحويل مساحتك.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.7,
        reviewCount: 98,
        phone: "+9647705566778",
        email: "sanaa.interiordesign@example.com",
        cityId: 1,
        categoryIds: [26],
        services: ["Space Planning", "Color Consultation", "Furniture Selection"],
        servicesAr: ["تخطيط المساحات", "استشارة الألوان", "اختيار الأثاث"],
        experienceYears: 9,
        priceRange: "40,000 - 70,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic", "English"],
        workingHours: "9:00 AM - 6:00 PM"
    },
    {
        name: "Fawaz Al-Basra",
        profession: "Event Planner",
        professionAr: "منظم فعاليات",
        bio: "Professional event planning services for all occasions.",
        bioAr: "خدمات تنظيم الفعاليات الاحترافية لجميع المناسبات.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.8,
        reviewCount: 105,
        phone: "+9647506677889",
        email: "fawaz.eventplanner@example.com",
        cityId: 2,
        categoryIds: [27],
        services: ["Wedding Planning", "Corporate Events", "Birthday Parties"],
        servicesAr: ["تخطيط حفلات الزفاف", "فعاليات الشركات", "حفلات أعياد الميلاد"],
        experienceYears: 5,
        priceRange: "45,000 - 75,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic"],
        workingHours: "10:00 AM - 7:00 PM"
    },
    {
        name: "Niran Al-Karkh",
        profession: "Photographer",
        professionAr: "مصورة",
        bio: "Capturing beautiful memories with professional photography.",
        bioAr: "التقاط ذكريات جميلة مع التصوير الفوتوغرافي الاحترافي.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.6,
        reviewCount: 112,
        phone: "+9647727788990",
        email: "niran.photographer@example.com",
        cityId: 3,
        categoryIds: [28],
        services: ["Wedding Photography", "Portrait Sessions", "Event Photography"],
        servicesAr: ["تصوير حفلات الزفاف", "جلسات تصوير شخصية", "تصوير الفعاليات"],
        experienceYears: 6,
        priceRange: "20,000 - 50,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic"],
        workingHours: "6:00 AM - 3:00 PM"
    },
    {
        name: "Ziad Al-Ramadi",
        profession: "Catering Service",
        professionAr: "خدمة تقديم الطعام",
        bio: "Delicious catering services for all your events.",
        bioAr: "خدمات تقديم الطعام اللذيذة لجميع فعالياتك.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.9,
        reviewCount: 85,
        phone: "+9647508899001",
        email: "ziad.catering@example.com",
        cityId: 4,
        categoryIds: [29],
        services: ["Wedding Catering", "Corporate Events", "Private Parties"],
        servicesAr: ["تقديم الطعام في حفلات الزفاف", "فعاليات الشركات", "حفلات خاصة"],
        experienceYears: 7,
        priceRange: "25,000 - 55,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic", "Kurdish"],
        workingHours: "7:00 AM - 4:00 PM"
    },
    {
        name: "Lamia Al-Sulaymaniyah",
        profession: "Delivery Service",
        professionAr: "خدمة توصيل",
        bio: "Fast and reliable delivery services for your needs.",
        bioAr: "خدمات توصيل سريعة وموثوقة لاحتياجاتك.",
        avatar: "https://images.unsplash.com/photo-1561222038-70b0a3012b43?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9vZmluZ3xlbnwwfHwwfHx8MTY5NzQyNDAyNHww&w=150&h=150&fit=crop",
        rating: 4.7,
        reviewCount: 102,
        phone: "+9647729900112",
        email: "lamia.delivery@example.com",
        cityId: 5,
        categoryIds: [30],
        services: ["Package Delivery", "Document Delivery", "Food Delivery"],
        servicesAr: ["توصيل الطرود", "توصيل المستندات", "توصيل الطعام"],
        experienceYears: 8,
        priceRange: "30,000 - 60,000 IQD",
        availability: "Available",
        portfolio: [],
        isVerified: true,
        languages: ["Arabic"],
        workingHours: "8:00 AM - 5:00 PM"
    }
];